public  class MathPractice {
    public Decimal practiceOne(Decimal p1, Decimal p2) {
        Decimal cevre= (p1+p2)*2 ;
        return cevre;
    }

    public Decimal practiceTwo(Decimal kilo,Decimal boy){
        Decimal VKI= kilo/(boy*boy);
        return VKI;
    }

    public Decimal practiceThree(Decimal num1, Decimal num2){
        Decimal orta= (num1+num2)/2;
        return orta; 
    }
}