public  class ReturnArthimaticalcalculation {
    //we are creating a method
    //method gets two integer vaule and sums them and stores the value in var z
    //and we store the result in return
    public integer addition(integer a,integer b) {
        Integer z= a+b;
        return z;
    }
    
    //we are creating a method
    //method gets two integer vaule and sums them and stores the value in var z
    //and we store the result in return
    public integer addition(integer a,integer b,Integer c,Integer d) {
        Integer x= a+b+c+d;
        return x;
    }
}